name: Publish

on:
  push:
    branches: ['ghactions']
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Run Docker
        run: |
          using: 'docker'
          image: 'dockerfiles/Dockerfile'
      
