name: Docker image CI

on:
  push:
    branches: ['ghactions']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . --file Dockerfile 
   
      
