name: Docker image CI

on:
  push:
    branches: ['dynamic_repo']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build . --tag ghcr.io/${{ GITHUB_REPOSITORY }}:latest
          docker push ghcr.io/${{ GITHUB_REPOSITORY }}:latest